name: bookly_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hydrated_bloc: ^10.1.1
  flutter_3d_controller: ^2.3.0
  freezed_annotation: ^3.1.0
  curved_navigation_bar: ^1.0.6
  animated_theme_switcher: ^2.0.10
  introduction_screen: ^4.0.0
  flutter_snake_navigationbar: ^0.6.1
  page_transition: ^2.2.1
  lottie: ^3.3.2
  get: ^4.7.2
  bot_toast: ^4.1.3
  shimmer: ^3.0.0
  collection: ^1.19.1
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.2.1
  easy_localization: ^3.0.8
  dartz: ^0.10.1
  http: ^1.5.0
  get_it: ^8.2.0
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  file_picker: ^10.3.3
  loading_animation_widget: ^1.3.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  skeletonizer: ^2.1.0+1
  page_flip: ^0.2.5+1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  injectable: ^2.5.2
  internet_connection_checker: ^3.0.1
  flutter_spinkit: ^5.2.2
  font_awesome_flutter: ^10.10.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.9.0
  build_runner: ^2.9.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/